version: 2

project_name: kpub

builds:
  - main: ./cmd/kpub
    binary: kpub
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

dockers_v2:
  - id: kpub
    dockerfile: Dockerfile
    images:
      - "ghcr.io/spacesedan/kpub"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
    flags:
      - "--pull"

nfpms:
  - package_name: kpub
    maintainer: spacesedan <spacesedan@users.noreply.github.com>
    homepage: https://github.com/spacesedan/kpub
    description: Telegram chat monitor and ebook pipeline for Kobo
    license: MIT
    formats:
      - deb
      - rpm

homebrew_casks:
  - name: kpub
    repository:
      owner: spacesedan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/spacesedan/kpub
    description: Telegram chat monitor and ebook pipeline for Kobo
    license: MIT
    dependencies:
      - formula: docker

changelog:
  sort: asc
